mantlenetworkio/mantle

ops/docker/hardhat/package.json

https://github.com/NomicFoundation/hardhat/pull/2581
Make `eth_getStorageAt` spec-compliant. This means that the storage slot argument **must** have a length of 32 bytes (a hex-encoded string of length 66).  For forge client.

upgrade hardhat network to ^2.12.0

---

l2geth/eth/api_backend.go
l2geth/rollup/sync_service.go

When a node recived a tx from api , we need do a pre check like `txpool.ValidateTx` and `syncService.verifyFee`

Add send tx sync service pre check

---

l2geth/eth/backend.go
l2geth/eth/consensus_handler.go
l2geth/eth/handler.go

Add peer check when scheduler has p2p connection with other nodes, only sequencers who registered in the contract and selected as sequencer by scheduler can connect with scheduler.

Peer check 

---

l2geth/miner/worker.go

When sequencer trying to pick out a set of transactions to build `BatchPeriodAnswerMsg`, duo to asynchronous txpool reorg, some txs with incorrect nonce will be included. As a result, the scheduler will drop the `BatchPeriodAnswerMsg`, abort the batch and punish this sequencer laster.

R4R: optimize tx selection algorithm for sequencer

---

tss/manager/manage.go
tss/manager/router/registry.go
tss/node/cmd/tssnode/cmd.go
tss/node/signer/delete_slash.go
tss/node/signer/process.go
tss/node/signer/verify_slash.go
tss/slash/slash.go
tss/slash/slash_node.go

Core changes:
- Remove the logic of calculating slash information for the tssnode portion and directly cache the slash information for nodes that do not participate each time.
- Put the logic of checking if tssnode is slashed in tssmanager, and let tssnode only verify.

fix bug in tss slash process

---

mt-batcher/services/sequencer/driver.go
mt-challenger/challenger/challenger.go

Core changes:
- TxAggregator() Might Cause a Panic Medium
- eventLoop() Does Not Abort the Current Ticker Loop if levelDB.GetLatestBatchIndex() Fails Major
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1042

[R4R] consensys audit fix for mt-batcher and mt-challenger

---

tss/manager/cmd.go

Core changes:
fixed this error:
```
manager/cmd.go:21:2: index redeclared in this block
manager/cmd.go:13:2: other declaration of index
manager/cmd.go:21:2: imported and not used: "github.com/mantlenetworkio/mantle/tss/index"
manager/cmd.go:22:2: l1chain redeclared in this block
manager/cmd.go:14:2: other declaration of l1chain
manager/cmd.go:22:2: imported and not used: "github.com/mantlenetworkio/mantle/tss/manager/l1chain"
manager/cmd.go:24:2: store redeclared in this block
manager/cmd.go:15:2: other declaration of store
manager/cmd.go:24:2: imported and not used: "github.com/mantlenetworkio/mantle/tss/manager/store"
manager/cmd.go:25:2: slash redeclared in this block
manager/cmd.go:16:2: other declaration of slash
manager/cmd.go:25:2: imported and not used: …
```

fix tss imports

---

gas-oracle/tokenprice/tokenprice.go
gas-oracle/tokenprice/tokenprice_test.go
gas-oracle/tokenprice/tokenprice_uniswap.go

resolves #1054 
Core changes:
- bounds check for eth_price, mnt_price & token_ratio
- #1054

[gasoracle]fix: bounds check for eth_price, mnt_price & token_ratio

---

gas-oracle/gasprices/gas_price_updater_test.go
gas-oracle/main.go
gas-oracle/metrics/metrics.go
gas-oracle/metrics/metrics_test.go
gas-oracle/oracle/base_fee.go
gas-oracle/oracle/da_fee.go
gas-oracle/oracle/gas_price_oracle.go
gas-oracle/oracle/l1_client.go
gas-oracle/oracle/overhead.go
gas-oracle/oracle/updater_interface.go

Core changes:
- Add metrics for gas oracle
Here are stats:
- TokenRatioGauge metrics.Gauge
- token_ratio = eth_price / mnt_price 
- L1BaseFeeGauge metrics.Gauge
- (l1_base_fee + l1_priority_fee) * token_ratio
- FeeScalarGauge metrics.Gauge
- value to scale the fee up by
- DaFeeGauge metrics.Gauge
- da_fee shows da gas price
- OverHeadGauge metrics.Gauge
- over_head, amortized cost of batch submission per transaction
- L1GasPriceGauge metrics.Gauge
- l1_base_fee + l1_priority_fee
- #1101

[R4R][gasoracle]feat: add metrics for gasoracle

---

gas-oracle/flags/flags.go
gas-oracle/gasprices/gas_price_updater_test.go
gas-oracle/oracle/config.go
gas-oracle/oracle/gas_price_oracle.go
gas-oracle/oracle/l1_client.go
gas-oracle/tokenprice/tokenprice.go
gas-oracle/tokenprice/tokenprice_test.go
gas-oracle/tokenprice/tokenprice_uniswap.go
gas-oracle/tokenprice/tokenprice_uniswap_test.go
gas-oracle/tokenprice/tokenprice_v1.go
gas-oracle/tokenprice/tokenprice_v1_test.go
gas-oracle/tokenprice/tokenprice_v5.go
gas-oracle/tokenprice/tokenprice_v5_test.go

Core changes:
- calculate eth_price, mnt_price from multi oracle, use `median` value of them
- use `index price` from cex instead of latest price
- add bounds check for eth_price, mnt_price and token_radio
- token_ratio = eth_price / mnt_price, and its bounds is derived from last token_ratio
- token_ratio: [tokenRatioMin, tokenRatioMax]
- tokenRatioMin := max(last_token_ratio*0.95, TokenRatioMin)
- tokenRatioMax := min(last_token_ratio*1.05, TokenRatioMax)
- TokenRatioMin: 100
- TokenRatioMax: 10000
- eth_price: (100, 1000000)
- mnt_price: (0.01, 100)
- add `TOKEN_PAIR_MNT_MODE` to choose use `BIT` or `MNT` to calculate `token_ratio`
- https://github.com/mantlenetworkio/mantle/issues/1054
Related PRs:
- https://github.com/mantlenetworkio/mantle/pull/1062

[gasoracle]feat: optimize how to query and calculate token ratio

---

packages/contracts/contracts/L1/delegation/DelegationShareBase.sol
packages/contracts/contracts/L1/fraud-proof/Rollup.sol
packages/contracts/contracts/L1/tss/TssGroupManager.sol
packages/contracts/contracts/L1/tss/TssStakingSlashing.sol
packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
Internal audit final check and fix
- MantleDa: investmentManager contracts need check strategy for staker staking
- MantleDa: BVM_EigenDataLayrChain contracts need check startL2Block == l2ConfirmedBlockNumber for data rollup init and conform
- Tss: TssGroupManager contracts need check  activeTssMembers.length > threshold + 1 for removeMember function
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1119

[R4R]Feature/internal audit check fix

---

batch-submitter/batch_submitter.go
batch-submitter/config.go
batch-submitter/flags/flags.go
batch-submitter/tss-client/client.go
tss/common/jwthandle.go

Core changes:
- Add jwt access token to batch-submitter
Notes:
- Previously, I added jwt access token to tss server, however, the client still doesn't support jwt token. In this PR, I add the jwt access token to client.
- https://github.com/mantlenetworkio/mantle/pull/854

R4R: add jwt to batch-submitter

---

tss/common/merkle_tree.go

Core changes:
- The Merkle Tree implementation encounters an out-of-bounds error when processing sets with a large number of elements exceeding 131,072.
-

[R4R] - {0.4.2}: fix audit issue from sigma

---

tss/node/tsslib/keysign/tss_keysign.go

Core changes:
- Return error messages to avoid null pointer exceptions from occurring

Return error messages to avoid null pointer exceptions from occurring.

---

batch-submitter/drivers/sequencer/encoding.go
batch-submitter/drivers/sequencer/encoding_test.go
fraud-proof/rollup/types/tx_batch.go
mt-challenger/challenger/challenger.go
mt-challenger/challenger/challenger_test.go

Core changes:
fix sigma audit MNT-11
Notes:
no
TBD

[R4R] - {0.4.2}: Bugfix/sigma mnt 11

---

l2geth/consensus/clique/clique.go

Core changes:
- bugfix: `gas limit upgrade` just  available for testnet, not mainnet
- mainnet's `gas limit` is set to `30,000,000` from genesis
- #1005

[R4R][l2geth]hotfix: fix update upgrade gas limit

---

CHANGELOG.md

Core changes:
add change log
Notes:
no
no

[fix]: add change log

---

mt-batcher/common/utils.go

- The GetMessageHash() function in mt-batcher/common/utils.go is not used anywhere in the codebase. Despite its potential use for calculating a formatted hash of a message, its inactivity could lead to confusion and potential compatibility issues.
no
https://github.com/mantlenetworkio/mantle/issues/1170

[R4R] - {develop}: Remove unuseless code in mt-batcher

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
- Emit an event on completion for resetRollupBatchData
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1173

[R4R] - {develop}: add event for resetRollupBatchData

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
- The functions removeFraudProofAddress() and unavailableFraudProofAddress() in the BVM_EigenDataLayrchain contract are equivalent so Remove unavailableFraudProofAddress() function.
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1175

[R4R] - {develop}: Remove unavailableFraudProofAddress function

---

tss/manager/agreement.go
tss/manager/keygen.go
tss/manager/manage.go
tss/manager/setup_test.go
tss/manager/sign.go
tss/manager/slash.go

Core changes:
- Use pointer instead of struct for tss manager
- https://github.com/mantlenetworkio/mantle/issues/1187

[R4R] - {develop}: fix consensys audit issue: cs-6.33

---

tss/node/tsslib/common/tss.go

Core changes:
- add default msg handler for function `ProcessOneMessage`
Notes:
[- Link issues here
](https://github.com/mantlenetworkio/mantle/issues/1195)

[R4R] - {develop}:add default msg handler for function `ProcessOneMessage`:cs-6.26

---

tss/node/server/http.go
tss/ws/server/handler.go

Core changes:
- replace `json.MarshalIndent` with `json.Marshal` to improve efficiency
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1209

[R4R] - {develop}: fix consensys audit issue: cs-6.40

---

tss/manager/agreement.go
tss/node/tsslib/keysign.go
tss/ws/server/handler.go

Core changes:
- Simplify error formatting by replacing instances of errors.New(fmt.Sprintf()) with the more streamlined fmt.Errorf() throughout the code base.
Notes:
[- Link issues here
](https://github.com/mantlenetworkio/mantle/issues/1192)

[R4R] - {develop}: Simplify error formatting

---

tss/common/types.go
tss/manager/keygen.go
tss/node/signer/keygen.go

Core changes:
- Query the threshold value of the TSSGroupManager smart contract and verify if the value in the keygen request is correct.
- https://github.com/mantlenetworkio/mantle/issues/1056

[R4R]:fix lock threshold validation

---

l2geth/core/types/gen_receipt_json.go
l2geth/core/types/receipt.go

Core changes:
- fix query transaction_receipt details with eth_getTransactionReceipt shows error with [l2geth](https://github.com/mantlenetworkio/mantle/tree/main/l2geth)
- #1233

[R4R] - {0.4.2} [l2geth] bugfix: transaction receipt unmarshal

---

tss/node/signer/keygen.go
tss/node/signer/sign.go
tss/node/signer/sign_rollback.go
tss/node/signer/sign_slash.go
tss/node/signer/verify.go
tss/node/signer/verify_rollback.go
tss/node/signer/verify_slash.go

Core changes:
- fix secure3 issue about "Returned value of function SendMsg not checked." Enhance handling of return values

[R4R]-{develop}: fix secure mtl-32

---

l2geth/go.mod

Core changes:
- l2geth exclude mantleDa dependence so that it can build binary
Notes:
- no
- no

[R4R]- {develop}: l2geth exclude mantleDa dependence so that it can build binary

---

l2geth/accounts/abi/bind/backends/simulated.go
l2geth/core/state_transition.go

Core changes:
- fix ignore error in NewStateTransition of l2geth
Notes:
- no
- no

[R4R]-{develop}: fix ignore error in NewStateTransition of l2geth

---

packages/sdk/src/adapters/standard-bridge.ts
packages/sdk/src/utils/contracts.ts

Core changes:
- Defines a mapping between `L1_MNT_ADDRESS` and `L2_CHAIN_ID` so that we can check against the correct `MNT` address in the standard-bridge.

[R4R] - {sdk}: align standard-bridge with selected chain

---

gas-oracle/metrics/metrics.go
gas-oracle/oracle/l1_client.go

Core changes:
- modify token_ratio from `int64` to `float64` for metrics
- solve the false alarm from monitor 
Issues:
- when using the `int64` data type, the changes on the decimal places will be eliminated
Solutions:
- replace `metrics.Gauge` with `metrics.GaugeFloat64` to store `token_ratio`
Results:

[R4R]-{develop}-[gasoracle]impr: modify token_ratio from int64 to float64 for metrics

---

gas-oracle/oracle/gas_price_oracle.go
gas-oracle/oracle/overhead.go

Core changes:
fix gasoracle update frequency
Notes:
no
no

[R4R]-{develop}: fix gasoracle update frequency

---

gas-oracle/oracle/base_fee.go

Core changes:
- Query `scalar` from gas_oracle contract and initialize `fee_scalar` for metrics when `gas_oracle` starts

[R4R]-{develop}-[gasoracle]impr: initialize fee_scalar metrics

---

CHANGELOG.md

Core changes:
- add change log for v0.4.3
Notes:
no
no

[R4R]-{develop}: change log for v0.4.3
