mantlenetworkio/mantle

packages/contracts/contracts/L1/tss/IStakingSlashing.sol
packages/contracts/contracts/L1/tss/ITssGroupManager.sol
packages/contracts/contracts/L1/tss/StakingSlashing.sol
packages/contracts/contracts/L1/tss/TssGroupManager.sol
packages/contracts/test/contracts/L1/tss/TssGroupMannager.ts
packages/contracts/test/contracts/L1/tss/stakingSlashing.ts

Add staking & slashing contract , update tss group contract

---

packages/fault-detector/src/helpers.ts
packages/fault-detector/src/service.ts

fix fault-detector

---

ops/docker-compose.yml

remove replica in gas-oracle

---

.circleci/config.yml
gas-oracle/oracle/gas_price_oracle.go
ops/docker-compose.yml

- dockerfile config gas oracle opne

open gas oracle base fee and gas price config

---

l2geth/accounts/accounts.go
l2geth/consensus/consensus.go
l2geth/consensus/coterie/api.go
l2geth/consensus/coterie/coterie.go
l2geth/consensus/coterie/snapshot.go

Implement coterie

---

.changeset/config.json
.circleci/config.yml
.github/workflows/goreleaser.yml
.github/workflows/publish-canary.yml
.github/workflows/release.yml
.github/workflows/sync-tests.yml
.gitignore
.goreleaser.yaml
DEVELOP.md
batch-submitter/CHANGELOG.md
batch-submitter/package.json
l2geth/README.md
ops/docker-compose.local.yml
ops/docker-compose.yml
ops/scripts/build-ci.sh

1. fix org name in image id to `bitnetworkio`. Will change again once our org name confirmed.
2. unified `batch-submitter` service name (remove `-service` suffix, it's useless)
3. fix changeset job 
4. add goreleaser job
5. integration-test disabled by default in docker-compose

fix: fix jobs

---

ops/goerli/testnet/Makefile.goerli.testnet.deploy

fix Makefile bug

---

packages/contracts/contracts/L1/sequencer/Sequencer.sol
packages/contracts/docs/Sequencer.md
packages/contracts/test/contracts/L1/sequencer/sequencer.spec.ts

Added several parameters and data that need to be displayed during use and provided a write interface

Update sequencer contract

---

packages/contracts/contracts/L2/predeploys/TssRewardContract.sol
packages/contracts/contracts/L2/predeploys/iTssRewardContract.sol
packages/contracts/docs/ITssRewardContract.md
packages/contracts/docs/TssRewardContract.md
packages/contracts/tasks/take-dump.ts

* fix TssRewardContract,batchTime update exception
* revert some local file

Fix tssReward contract.batchTime  update exception (#299)

---

ops/scripts/deployer.sh

"For the qa environment, totalSupply in the genesis file should be 0"

change totalsupply for qa enviroment

---

l2geth/consensus/clique/clique.go
l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_test.go
l2geth/consensus/clique/snapshot.go
l2geth/core/types/scheduler.go
l2geth/eth/api_backend.go
l2geth/eth/backend.go
l2geth/eth/consensus_handler.go
l2geth/eth/handler.go
l2geth/eth/peer.go
l2geth/miner/worker.go
l2geth/rollup/sync_service.go

- Scheduler generate and broadcast BatchPeriodStartMsg
- Sequencer handle BatchPeriodStartMsg, if the miner address is matched, pick tx from txpool and produce block

R4R: Implement scheduler and sequencer produce block inturn

---

l2geth/consensus/clique/clique.go
l2geth/consensus/clique/scheduler.go
l2geth/core/blockchain.go
l2geth/core/rawdb/accessors_chain.go
l2geth/core/state_processor.go
l2geth/eth/backend.go
l2geth/eth/handler.go
l2geth/eth/peer.go
l2geth/eth/protocol.go
l2geth/miner/worker.go
l2geth/rollup/sync_service.go

Close https://github.com/mantlenetworkio/mantle/issues/396

R4R: fix sync serice consistency issue

---

l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_test.go
l2geth/consensus/clique/sequencer.go
l2geth/consensus/clique/sequencer_set_test.go
l2geth/consensus/clique/sequencer_test.go
l2geth/core/events.go
l2geth/core/types/scheduler.go
l2geth/eth/backend.go
l2geth/eth/consensus_handler.go
l2geth/eth/handler.go
l2geth/p2p/server.go

Scheduler will check peer ID when add peers,Only peerids registered in the contract can connect with Scheduler node.
close #379

P2P ID Check When Add Peer

---

l2geth/cmd/geth/main.go
l2geth/cmd/geth/retesteth.go
l2geth/cmd/utils/flags.go
l2geth/consensus/clique/clique.go
l2geth/consensus/clique/clique_test.go
l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_test.go
l2geth/consensus/clique/snapshot.go
l2geth/consensus/consensus.go
l2geth/consensus/ethash/sealer.go
l2geth/core/blockchain.go
l2geth/core/events.go
l2geth/core/state_processor.go
l2geth/core/tx_pool.go
l2geth/core/types/scheduler.go
l2geth/eth/api_backend.go
l2geth/eth/backend.go
l2geth/eth/consensus_handler.go
l2geth/eth/consensus_protocol.go
l2geth/eth/handler.go
l2geth/eth/peer.go
l2geth/miner/miner.go
l2geth/miner/worker.go
l2geth/rollup/config.go
l2geth/rollup/sync_service.go
l2geth/rollup/sync_service_test.go

Close https://github.com/mantlenetworkio/mantle/issues/414

WIP: Only scheduler can produce block, other sequencer only propose tx set

---

l2geth/consensus/clique/scheduler.go
l2geth/eth/backend.go
l2geth/eth/consensus_handler.go
l2geth/eth/handler.go
l2geth/miner/worker.go

#336 task1 : Take a batch period from the batch period set, then construct BatchPeriodStartMsg and broadcast it
close #334

Add scheduler select miner

---

l2geth/consensus/clique/clique.go
l2geth/consensus/clique/snapshot.go
l2geth/eth/backend.go
l2geth/params/config.go

close https://github.com/mantlenetworkio/mantle/issues/465

R4R: donot check authority in verifier mode

---

CHANGELOG.md

add release 0.2.0 release notes

add release 0.2.0 release notes

---

.github/workflows/gh-pages.yaml

ceate a workflow job to deploy sdk docs for ghpages

add_sdk_workflow_job

---

l2geth/consensus/clique/clique.go

pickout missing change in PR 465
Co-authored-by: HaoyangLiu <users.noreply.github.com>

R4R: Pick out missing change in PR 465

---

go.work
l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/synchronizer/server.go
l2geth/eth/consensus_handler.go
l2geth/miner/worker.go
l2geth/rollup/sync_service.go

R4R: Update comment and fix bugs

---

tss/manager/manage.go

when tss manager get same request to signature. tss will return signature in store.
there is a bug when get signature from store . it returns with wrong data struct.

fix bug when tss manager get signature from store

---

l2geth/core/rawdb/rollback_state.go

close https://github.com/mantlenetworkio/mantle/issues/548

R4R: Fix read rollback states

---

l2geth/core/events.go
l2geth/core/types/scheduler.go
l2geth/eth/consensus_handler.go
l2geth/eth/consensus_protocol.go
l2geth/eth/handler.go
l2geth/eth/peer.go

R4R: Fix p2p consensus msgs double set as known

---

CHANGELOG.md

add 0.2.0 changelogs

---

ops/config/tss-node-config.toml
tss/common/config.go
tss/node/cmd/tssnode/cmd.go

add http server port in config file
fix metrics didn't work

add http server port in config file

---

l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_health.go
l2geth/core/types/scheduler.go
l2geth/eth/consensus_handler.go
l2geth/eth/peer.go
l2geth/miner/worker.go

close https://github.com/mantlenetworkio/mantle/issues/549

R4R: fix scheduler boundary issue

---

LICENSE

wb: update mit license 2020-2022 optimism

---

l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_health.go
l2geth/miner/worker.go

close https://github.com/mantlenetworkio/mantle/issues/572

R4R: fix issues in healthy assessor

---

l2geth/consensus/clique/clique.go

Close https://github.com/mantlenetworkio/mantle/issues/581

R4R: only include signer in epoch height

---

ops/scripts/deployer.sh

optimize TERM signal handling for docker image

fix deployer.sh

---

go.work
l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_health.go
l2geth/consensus/clique/synchronizer/server.go
l2geth/eth/consensus_handler.go
l2geth/eth/handler.go

Update decentralized sequencer code annotate

---

batch-submitter/drivers/proposer/driver.go
l2geth/cmd/geth/main.go
l2geth/cmd/geth/usage.go
l2geth/cmd/utils/flags.go
l2geth/consensus/clique/scheduler.go
l2geth/eth/api_backend.go
l2geth/eth/backend.go
l2geth/miner/worker.go
l2geth/rollup/config.go
l2geth/rollup/sync_service.go

close https://github.com/mantlenetworkio/mantle/issues/605

R4R: import rollup role to simplify devops

---

batch-submitter/drivers/proposer/driver.go

there is a bug about index out of range in batch submitter.
when rollback appears, at the same time, blocks range is bigger than limit in config . 
The bug will be reappear.

fix bug in batchsubmitter

---

packages/contracts/contracts/L1/fraud-proof/Rollup.sol
packages/contracts/contracts/L1/fraud-proof/challenge/Challenge.sol
packages/contracts/test/contracts/L1/fraud-proof/RollUp.ts

WIP: Fraud proof contract test

---

fraud-proof/proof/prover_test.go
fraud-proof/rollup/services/base.go
fraud-proof/rollup/services/sequencer/sequencer.go
fraud-proof/service.go
l2geth/cmd/geth/main.go
l2geth/cmd/utils/flags.go
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

Main Purpose:
* l2geth start up with initial stake on  init assertion

WIP: Feature/fraud proof stake

---

l2geth/miner/worker.go

close https://github.com/mantlenetworkio/mantle/issues/625

R4R: disable txSetProof

---

tss/manager/agreement.go
tss/manager/manage.go
tss/node/signer/verify.go

- there is a bug in websocket. we can not stop channel while websocket using to send message

can not stop channel before websocket,otherwise deadlock occurs

---

l2geth/cmd/utils/flags.go
l2geth/consensus/clique/scheduler.go
l2geth/consensus/clique/scheduler_health.go
l2geth/miner/miner.go
l2geth/miner/worker.go
l2geth/rollup/sync_service.go

* Close https://github.com/mantlenetworkio/mantle/issues/694
* Close https://github.com/mantlenetworkio/mantle/issues/603
* Bugfix for struct deep copy issue, tx hash panic 
* Bugfix in UpdateSyncServiceState, concurrent issue for verifier node

R4R: Optimize d-sequencer

---

packages/contracts/contracts/L1/fraud-proof/IRollup.sol
packages/contracts/contracts/L1/fraud-proof/Rollup.sol
packages/contracts/contracts/L1/fraud-proof/WhiteList.sol
packages/contracts/deploy/019-BVM_FraudProof.deploy.ts
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

add whitelist to fraud-proof stake
Core changes:
add whitelist contract to rollup.sol
https://github.com/mantlenetworkio/mantle/issues/717

[Fraud Proof]: add stake whitelist

---

batch-submitter/drivers/proposer/driver.go
fraud-proof/rollup/types/tx_batch.go

Core changes:
Add status check before batch submitter roll up
#689

Add batch submitter status check

---

fraud-proof/proof/proof/state_proof.go
fraud-proof/proof/prover.go
fraud-proof/rollup/services/base.go
fraud-proof/rollup/services/validator/validator.go
packages/contracts/contracts/L1/fraud-proof/challenge/Challenge.sol
packages/contracts/contracts/L1/fraud-proof/verifier/test-driver/VerifierTestDriver.sol
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

revert degub info in osp branch
Core changes:
* remove console log in contracts
* revert constructed challenge in validator
Notes:
no
no

[fix]: fix details

---

batch-submitter/drivers/sequencer/driver.go

Core changes: 
- fix end from da invalid memory address or nil pointer dereference bug
Notes:

fix end from da invalid memory address or nil pointer dereference bug

---

packages/data-transport-layer/src/services/da-ingestion/service.ts
packages/data-transport-layer/src/services/main/service.ts
packages/data-transport-layer/src/services/run.ts

Core changes:
- fix dtl sync eigenda bug
Notes:

fix dtl sync eigenda bug

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- dtl da init bug fix
Notes:
- no
- no

dtl da init bug fix

---

packages/data-transport-layer/src/services/da-ingestion/service.ts
packages/data-transport-layer/src/services/run.ts

Core changes:
- fix dtl sync eigenlayer step bug
Notes:
- no
- no

fix dtl sync eigenlayer step bug

---

fraud-proof/cmd/flags.go
fraud-proof/rollup/services/config.go
fraud-proof/rollup/services/sequencer/sequencer.go
fraud-proof/rollup/services/validator/validator.go
l2geth/cmd/geth/main.go
l2geth/cmd/utils/flags.go
packages/contracts/contracts/L1/fraud-proof/challenge/Challenge.sol
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

Verifier re-stake and Sequencer challenge verify

Add verifier re-stake check and challenge verifiery

---

batch-submitter/drivers/proposer/driver.go
batch-submitter/drivers/sequencer/driver.go
batch-submitter/drivers/sequencer/metrics.go
fraud-proof/bindings/gen.go
fraud-proof/proof/prover.go
fraud-proof/proof/test_api.go
fraud-proof/rollup/services/sequencer/sequencer.go
fraud-proof/rollup/services/utils.go
fraud-proof/rollup/services/validator/validator.go
packages/contracts/contracts/L1/fraud-proof/verifier/VerifierEntry.sol
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json
packages/contracts/tasks/fraud-proof-tasks.ts
tss/node/signer/deal_msg.go
tss/node/signer/delete_slash.go
tss/node/signer/dial_le_client.go
tss/node/signer/keygen.go
tss/node/signer/process.go
tss/node/signer/sign.go
tss/node/signer/sign_rollback.go
tss/node/signer/sign_slash.go
tss/node/signer/verify.go
tss/node/signer/verify_rollback.go
tss/node/signer/verify_slash.go

Core changes:
-  Modified only owner for VerifierEntry contract
-  Remove challenge test code
-  Update verifier deploy caller
#754

Fraud proof verfy osp code clean

---

packages/contracts/contracts/test-helpers/TestUpgrade.sol
packages/contracts/tasks/upgrade-task.ts

Set upgrade test task for contract  `TransparentUpgradeableProxy`

Update proxy upgrade task

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
- da contract slot for upgrade change
Notes:

da contract slot for upgrade change

---

ops/scripts/deployer.sh
packages/contracts/contracts/L1/fraud-proof/WhiteList.sol
packages/contracts/deploy/019-BVM_FraudProof.deploy.ts
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json
packages/contracts/src/address-names.ts
packages/contracts/tasks/fraud-proof-tasks.ts
packages/contracts/tasks/upgrade-task.ts

Add tasks for fraud proof contract deploy and init

Add fraud stake and white list init tasks

---

l2geth/cmd/geth/main.go
l2geth/cmd/geth/usage.go
l2geth/cmd/utils/flags.go
l2geth/rollup/client_v2.go
l2geth/rollup/config.go
l2geth/rollup/eigenda/client.go
l2geth/rollup/sync_service.go
packages/data-transport-layer/src/services/da-ingestion/service.ts
packages/data-transport-layer/src/services/run.ts

Core changes:
- verifier can sync data from eigen retriver and data layer transport
Notes:

verifier support sync data from da retriver and data layer transport

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- fix dtl chainid config
Notes:

fix chainid config

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- metrics for da dtl improve and fix
Notes:

feat: dtl metrics opt for monitor

---

mt-batcher/services/sequencer/driver.go

Core changes:
- fix config for mt batcher
Notes:

fix config for mt batcher

---

mt-batcher/services/sequencer/driver.go

Core changes:
- fix wallet fee address config
Notes:

fix wallet fee address config

---

l2geth/rollup/sync_service.go

Core changes:
- update da verifier sync bug
Notes:

update da verifier sync bug

---

packages/contracts/package.json
packages/data-transport-layer/package.json
packages/data-transport-layer/src/services/l1-ingestion/handlers/state-batch-appended.ts
packages/sdk/package.json
packages/sdk/src/cross-chain-messenger.ts
packages/sdk/src/interfaces/types.ts
packages/sdk/src/utils/contracts.ts

Core changes:
Update some packages to support the upgrade of fraudProof

Update some packages to support the upgrade of fraudProof

---

packages/contracts/contracts/L1/messaging/L1StandardBridge.sol
packages/contracts/contracts/L1/tss/TssGroupManager.sol
packages/contracts/contracts/L1/tss/TssStakingSlashing.sol
packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol
packages/contracts/contracts/da/BVM_EigenDataLayrFee.sol

fix bridge bugs by internal audit
Notes:
no
no

[fix]: fix internal audit bugs

---

packages/contracts/contracts/L1/messaging/L1StandardBridge.sol
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

bump 0.4.0 da submodules, fix details
Notes:
no
no

[fix]: fix bump eigen submodule

---

packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json
packages/contracts/tasks/fraud-proof-tasks.ts

comment l1 mint call
Notes:
no
no

comment l1 mint call

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- add da batch index into transaction
Notes:

feat: add da batch index into transaction

---

ops/scripts/batch-submitter.sh

Core changes:
- feat: fix batch submitter script
Notes:

feat: fix batch submitter script

---

packages/contracts/deploy-config/goerli-testnet.ts

Core changes:
- modify eigenDaBlock to 8280000 for upgrade
Notes:

feat: modify eigenDaBlock to 8280000 for upgrade

---

l2geth/consensus/clique/clique.go
l2geth/core/genesis.go
l2geth/params/config.go

https://github.com/mantlenetworkio/mantle/pull/852/files

wb:fix genesis bug

---

packages/contracts/deploy-config/goerli-testnet.ts

Core changes:
- modify eigenDaBlock to 8280000 for testnet upgrade
Notes:

feat: modify eigenDaBlock to 8280000 for upgrade (#888)

---

packages/contracts/tasks/fraud-proof-tasks.ts

add staker

---

metrics/namespace.go
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

[fix]: fix concurrent map r/w

---

fraud-proof/rollup/services/validator/validator.go
packages/contracts/genesis/local.json
packages/contracts/genesis/state-dump.latest.json

fix fraud verifier get block nil pointer
Notes:
no
no

[fix]: fix get block nil pointer

---

batch-submitter/drivers/proposer/driver.go
fraud-proof/cmd/flags.go
l2geth/cmd/utils/flags.go
ops/scripts/geth.sh

[fix]: import-fp-operator-key-into-l2geth

---

fraud-proof/rollup/services/validator/validator.go
gas-oracle/oracle/base_fee.go

set default base fee
Notes:
no
no

[fix]: set default base fee

---

packages/contracts/deploy/019-BVM_FraudProof.deploy.ts
packages/contracts/tasks/fraud-proof-tasks.ts

twist fraud proof task
Notes:
no
no

[fix]: twist fraud proof task

---

packages/contracts/contracts/L1/fraud-proof/Rollup.sol

delete unused import
Notes:
no
no

[fix]: delete unsecessary import from rollup

---

fraud-proof/bindings/Rollup.go

[fix]: fix rollup binding

---

gas-oracle/oracle/base_fee.go
gas-oracle/oracle/l1_client.go

[fix]: fix HeaderByNumber

---

packages/contracts/contracts/L1/fraud-proof/WhiteList.sol

fix whitelist update logics
Notes:
no
no

[fix]: fix whitelist update

---

packages/data-transport-layer/src/services/l1-ingestion/handlers/state-batch-appended.ts
packages/data-transport-layer/src/services/l1-ingestion/handlers/state-cached-batch-appended.ts
packages/sdk/src/cross-chain-messenger.ts

add try catch into sdk
Notes:
no
no

[fix]: add try catch with event StateBatch parse

---

packages/contracts/contracts/L1/rollup/StateCommitmentChain.sol
tss/manager/store/storage.go
tss/node/store/storage.go

Core changes:
- Resolve code optimization issues mentioned in code review

Audit fix tss

---

mt-batcher/services/sequencer/driver.go

Core changes:
- fix mt-batcher waitGroup
Notes:

feat: fix mt-batcher waitGroup

---

packages/contracts/contracts/L1/fraud-proof/Rollup.sol

fix require

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
- fix contract for hsm
Notes:

feat: fix contracts for hsm

---

packages/contracts/contracts/L1/rollup/StateCommitmentChain.sol

Core changes:
- fix bug in scc contract

fix bug in scc contract

---

mt-challenger/Makefile

Core changes:
- fix mt-challenger make file bug
Notes:

feat: fix mt-challenger make file bug

---

fraud-proof/service.go
gas-oracle/oracle/base_fee.go

hotfix: fix error crit

---

l2geth/eth/api_backend.go
l2geth/internal/ethapi/api.go
l2geth/rollup/client.go

Core changes:
- hotfix : fix gettxstatus when backend = l2

[Hotfix/0.4.0 ]testnet txstatus

---

l2geth/eth/api_backend.go
l2geth/internal/ethapi/api.go
l2geth/rollup/client.go

Core changes:
- fix txstatus when backend = l2

[hotfix/0.4.0] txstatus 

---

mt-batcher/services/sequencer/driver.go

bugfix : fix opts nil pointer

---

mt-batcher/Dockerfile
mt-challenger/Dockerfile
tss/Dockerfile

Core changes:
- remove package `jq` `curl` from Dockerfile for security enhancement

remove useless packages

---

.github/workflows/close-stale.yml

Core changes:
- change pr stale days to 30

change pr stale days to 30

---

packages/data-transport-layer/src/services/l1-ingestion/service.ts

Notes:
**Screenshots**
test0_withdraw succeed.
#1003

[R4R] bugfix: remove rebundant code in dtl

---

packages/contracts/deploy-config/goerli-qa.ts
packages/contracts/deploy-config/goerli-testnet.ts
packages/contracts/deploy-config/hardhat.ts

fix deploy config
Notes:
no
no

[R4R]: Bugfix/add proxy l1 mantle address

---

CHANGELOG.md

update change log version
Notes:
no
no

[R4R]: fix changelog title

---

gas-oracle/go.sum
gas-oracle/oracle/overhead.go
packages/contracts/genesis/local.json

fix gasoracle overhead update for hsm
Notes:
no
no

[R4R]: fix gasoracle hsm

---

packages/data-transport-layer/src/services/da-ingestion/service.ts
packages/data-transport-layer/src/services/main/service.ts
packages/data-transport-layer/src/services/run.ts
packages/data-transport-layer/src/services/server/service.ts
packages/data-transport-layer/src/types/api-types.ts
tss/manager/cmd.go

Core changes:
Add timeout for DA ingestion API integration
Remove test code in dtl
Levelup codebase handle, fork this codebase and self maintenance
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1044

[R4R]Feature/fix dtl for consensys audit

---

tss/manager/cmd.go

Core changes:
- fix tss gomod
Notes:
- no
- no

[R4R]Bugfix/fix tss gomod

---

batch-submitter/batch_submitter.go
batch-submitter/drivers/proposer/driver.go

[R4R]: revert batchsubmmiter config for hsm

---

tss/node/signer/verify.go

Core changes:
- When there is a large amount of state root that needs to be verified, there is a bottleneck in the query performance of the da-verifier. Now, instead of verifying all state roots previously, only the last state root is verified.

only verify the last block stateroot

---

tss/Dockerfile

fix tss docker file build exception
Notes:
no
no

[R4R]: Bugfix/fix tss dockerfile

---

packages/contracts/contracts/L1/tss/ITssGroupManager.sol
packages/contracts/contracts/L1/tss/ITssStakingSlashing.sol
packages/contracts/contracts/L1/tss/TssGroupManager.sol
packages/contracts/contracts/L1/tss/TssStakingSlashing.sol
packages/contracts/contracts/L2/predeploys/TssRewardContract.sol
packages/contracts/contracts/L2/predeploys/iTssRewardContract.sol
packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol
packages/contracts/contracts/da/BVM_EigenDataLayrFee.sol
packages/contracts/contracts/libraries/utils/Lib_Address.sol
packages/contracts/contracts/test-helpers/FailingReceiver.sol
packages/contracts/tasks/take-dump.ts

Core changes:
- Fixing issues raised during code audit.
- #1091 
- #1092 
- #1093 
- #1094 
- #1098

[R4R]Audit fix tss contract

---

gas-oracle/oracle/gas_price_oracle.go
mt-batcher/services/sequencer/driver.go
packages/contracts/contracts/L1/delegation/DelegationShareBase.sol

Core changes:
fix erc20 call decimals
enrich necessary log
Notes:
no
https://github.com/mantlenetworkio/mantle/issues/1087

[fix]: enrich log, fix erc20 call decimal

---

packages/contracts/contracts/L1/tss/ITssStakingSlashing.sol
packages/contracts/contracts/L1/tss/TssStakingSlashing.sol
packages/contracts/deploy-config/goerli-qa.ts
packages/contracts/deploy-config/goerli-testnet.ts
packages/contracts/deploy-config/hardhat.ts
packages/contracts/deploy-config/local.ts
packages/contracts/deploy-config/mainnet.ts
packages/contracts/deploy/010-TssContracts.ts
packages/contracts/hardhat.config.ts
packages/contracts/src/deploy-config.ts

Core changes:
- fix audit issue
- #1116

[R4R]fix audit issue about slashing function in TssStakingSlashing

---

packages/contracts/contracts/L1/messaging/L1StandardBridge.sol

Core changes:
- remove unused func
Notes:

[R4R]: remove unused func

---

packages/contracts/contracts/L1/messaging/L1StandardBridge.sol
packages/contracts/contracts/L2/messaging/L2StandardBridge.sol

Core changes:
- add messenger address check for L1StandardBridge 
Notes:

[R4R]: add messenger address check to bridge

---

gas-oracle/oracle/da_fee.go
gas-oracle/oracle/overhead.go
gas-oracle/tokenprice/tokenprice.go
gas-oracle/tokenprice/tokenprice_uniswap.go

Core changes:
- enrich logs for gas oracle, especially for calculating token ratio

[gasoracle]feat: enrich logs for gas oracle

---

CHANGELOG.md

Core changes:
* Hotfix/fix releasev0.4.1 beta.0 (#1109)
* remove hsm credential in log
* fix changelog title (#1028)
* fix tss docker file
Notes:
no
no

[R4R] - {0.4.2}: Hotfix/fix releasev0.4.1 beta.0 (#1109) (#1110)

---

packages/contracts/contracts/L1/deployment/ChugSplashDictator.sol

change messengerSlotKey,messengerSlotVal, bridgeSlotKey,bridgeSlotVal, mantleAddressSlotKey,mantleAddressSlotVal to immutable type.
Notes:
close https://github.com/mantlenetworkio/mantle/issues/1113

[R4R] - {audit-fix}: fix secure3 audit MTL-43

---

tss/manager/sign.go
tss/node/tsslib/keysign.go
tss/node/tsslib/keysign/tss_keysign.go
tss/node/tsslib/storage/shamir_mgr.go
tss/ws/server/handler.go

Core changes:
- Ensure key length is no less than 16
- Add Signature’s size verification
Notes:
- close https://github.com/mantlenetworkio/mantle/issues/1127
- close https://github.com/mantlenetworkio/mantle/issues/1129
- close https://github.com/mantlenetworkio/mantle/issues/1130

[R4R] - {0.4.2}: Resolve audit feedback from Sigma: MNT-9, MNT-10 and MNT-12

---

proxyd/cache.go

Core changes:
- Fix unreachable error handling
- close https://github.com/mantlenetworkio/mantle/issues/1136

[R4R] - {0.4.2}: Resolve audit feedback from Sigma: MNT23

---

fraud-proof/proof/state/stack.go

Core changes:
fix sigma audit MNT-30
Notes:
no
TBD

[R4R] - {0.4.2}: Bugfix/sigma mnt 30

---

packages/data-transport-layer/src/services/server/service.ts

Core changes:
- fix dtl tx status api bug
Notes:
- no
- no

[R4R]: fix dtl tx status api bug

---

integration-tests/package.json
mt-challenger/go.mod
mt-challenger/go.sum
packages/contracts/package.json
packages/data-transport-layer/package.json
packages/fault-detector/package.json
packages/message-relayer/package.json
packages/sdk/package.json
yarn.lock

Core changes:
- contracts module upgrade
- all dependent contracts node package upgrade
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1148

[R4R]: node package version upgrade for release 0.4.2

---

CHANGELOG.md

Core changes:
add change log
Notes:
no
no

[R4R] - {0.4.2}: add change log

---

mt-batcher/services/client/client.go
mt-batcher/services/restorer/service.go
packages/data-transport-layer/src/services/server/service.ts
packages/data-transport-layer/src/types/database-types.ts

Core changes:
- Fix dtl api transaction status
- Fix mt-batcher context and enqueue.Origin
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1162

[R4R]: fix dtl tx status

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- fix dtl datastore bug
Notes:
- no
- no

fix dtl datastore bug

---

packages/contracts/deploy-config/goerli-qa.ts
packages/contracts/deploy-config/local.ts

Core changes:
fix deployer config
Notes:
no
no

[R4R] - {0.4.2}: fix deployer config

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
- fix BVM_EigenDataLayrChain contract logic
Notes:
- no
- no

[R4R]: fix BVM_EigenDataLayrChain contract logic

---

l2geth/rollup/sync_service.go

Core changes:
- Change sync batch range in syncEigenTransactionBatchRange function
Notes:
- no
- no

[R4R] - {0.4.2}: Hotfix/fix verifer sync range

---

CHANGELOG.md
l2geth/rollup/sync_service.go
packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol

Core changes:
fix BVM_EigenDataLayrChain contract logic
Notes:
no
no

[R4R] - {0.4.2}: fix BVM_EigenDataLayrChain contract logic

---

mt-batcher/services/sequencer/driver.go
tss/manager/sign_test.go
tss/node/tsslib/keysign.go
tss/node/tsslib/p2p/communication.go
tss/node/tsslib/tss.go

Core changes:
- Fix audit issue from Consensys: cs-6.45, cs-6.44 and cs-6.43
- https://github.com/mantlenetworkio/mantle/issues/1182
- https://github.com/mantlenetworkio/mantle/issues/1178
- https://github.com/mantlenetworkio/mantle/issues/1177

[R4R] - {develop}: fix consensys minor audit issue: cs-6.43, cs-6.44 and cs-6.45

---

tss/node/cmd/tssnode/cmd.go
tss/node/tsslib/tss.go

Core changes:
- quit process when log error msg.
Notes:
[- Link issues here
](https://github.com/mantlenetworkio/mantle/issues/1186)

[R4R] - {develop}: fix consensys audit issue: cs-6.22

---

tss/node/tsslib/abnormal/abnormal.go
tss/node/tsslib/abnormal/manager.go
tss/node/tsslib/abnormal/policy.go
tss/node/tsslib/abnormal/types.go
tss/node/tsslib/common/tss.go

Core changes:
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1189

[R4R] - {develop}: fix consensys audit issue: cs-6.34

---

tss/node/tsslib/common/tss.go
tss/node/tsslib/conversion/conversion.go
tss/node/tsslib/keygen/tss_keygen.go
tss/node/tsslib/keysign/tss_keysign.go

Core changes:
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1200
- https://github.com/mantlenetworkio/mantle/issues/1208

[R4R] - {develop}: fix consensys audit issue: cs-6.14

---

tss/node/tsslib/storage/secrets_mgr.go
tss/node/tsslib/storage/shamir_mgr.go
tss/node/tsslib/tss.go

Core changes:
- Fix `Msgf` directives
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1205

[R4R] - {develop}: fix consensys audit issue: cs-6.37

---

tss/manager/router/registry.go

Core changes:
- return bad request if request type is unsupported
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1211

[R4R] - {develop}: fix consensys audit issue: cs-6.42

---

tss/manager/l1chain/service.go

Core changes:
- Return err instead of nil
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1218

[R4R] - {develop}: fix consensys audit issue: cs-6.30

---

mt-batcher/config.go
mt-batcher/flags/flags.go
mt-batcher/mt_batcher.go
mt-batcher/services/restorer/service.go
mt-batcher/services/sequencer/driver.go

Core changes:
remove unused struct for mnt-37 
Notes:
[- Link issues here
](https://github.com/mantlenetworkio/mantle/issues/1184)

[R4R] - {develop}: remove unused struct for mnt-37 

---

tss/node/tsslib/keysign.go

R4R: fix compile error

---

tss/manager/router/registry.go
tss/manager/sign.go

Core changes:
- log error message for unrecognized error code
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1216

[R4R] - {develop}: fix consensys audit issue: cs-6.35

---

ops/config/tss-manager-config.toml
ops/config/tss-node-config.toml

Core changes:
- fix issue about read jwt secret key failure in config
Notes:
- https://github.com/mantlenetworkio/mantle/issues/1225

R4R: fix jwt secret key config issue

---

gas-oracle/metrics/metrics.go

Core changes:
- fix metrics for gas oracle

[R4R] - {0.4.2}[gasoracle]bugfix: modify gasoracle metrics

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- fix upgrade da tool
Notes:
- no
- no

[R4R] - {0.4.2}:Bugfix/upgrade da tool

---

packages/data-transport-layer/src/services/da-ingestion/service.ts
packages/data-transport-layer/src/services/l1-ingestion/service.ts

Core changes:
- fix dtl sync data from mantleDa bug
Notes:
- no
- no

[R4R] - {0.4.2}: fix dtl sync data bug

---

README.md

[R4R] - {develop}: delete outdated description

---

packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
- Fix dtl sync data bug
Notes:
- no
- no

fix dtl sync data bug

---

README.md
packages/data-transport-layer/src/services/da-ingestion/service.ts

Core changes:
fix dtl sync batch requirement
Notes:
no
no

[R4R] - {0.4.2}: fix dtl sync data bug (#1258)

---

tss/ws/client/tm/client.go

Core changes:
- fix audit mnt-35 from sigma

[R4R] - {develop}: fix sigma MNT-35

---

CHANGELOG.md

Core changes:
release 0.4.2 change log
Notes:
no
no

[R4R] - {0.4.2}: Changelog/changelog v0.4.2

---

packages/contracts/contracts/da/BVM_EigenDataLayrChain.sol
packages/contracts/contracts/da/BVM_EigenDataLayrFee.sol

Core changes:
- fix  Missing 0 address check in any contracts
Notes:
- no
- no

[R4R]-{develop}: fix  Missing 0 address check in any contracts

---

packages/contracts/contracts/L2/tokens/wmantle.sol

Core changes:
- modify WMANTLE9 to WMANTLE
- modify token name to "Wrapped Mantle"
- modify token symbol to "WMNT" 
Notes:
- no
- no

[R4R] - {develop}: modify WMANTLE9 to WMANTLE

---

bss-core/service.go
bss-core/txmgr/txmgr.go

Core changes
ignore unimportant error log
Notes:
no
no

[R4R] - {develop}: Bugfix/eliminate unimportant error log, merge main into develop

---

l2geth/core/state_transition.go

Core changes:
- fix l2geth error judge
Notes:
- no
- no

[R4R]-{develop}: fix l2geth error judge

---

l2geth/eth/api_tracer.go

Core changes:
- add nil pointer checker in traceCall
Notes:
- close https://github.com/mantlenetworkio/mantle/issues/1304

R4R: fix panic in traceCall

---

l2geth/eth/api_tracer.go

Core changes:
- hotfix debug trace panic when tracer is nil
Notes:
- close https://github.com/mantlenetworkio/mantle/issues/1304

R4R: Hotfix debug tract panic for release0.4.2

---

.forkop

Core changes:
- change fork version information
Notes:
- no
- no

change fork version maintain info

---

l2geth/internal/ethapi/api.go

https://github.com/mantlenetworkio/mantle/issues/1317

bugfix: rename rollup to 'Accepted on layer1'

---

packages/contracts/contracts/da/BVM_EigenDataLayrFee.sol

Core changes:
- MantleDa fee can be set to 0, but there is a limit greater than 0 in the code, it should be remove.
Notes:
- no
- https://github.com/mantlenetworkio/mantle/issues/1319

[R4R]-{develop}: remove invalid logical condition

---

CONTRIBUTING.md
gas-oracle/README.md
l2geth/README.md
ops/README.md

[R4R]-{develop}: Fix typos

---

CONTRIBUTING.md
README.md
fraud-proof/LICENSE
gas-oracle/README.md
l2geth/README.md
ops/README.md

Core changes:
sync develop
Notes:
no
no

V0.4.3/sync develop

---

l2geth/Makefile

Core changes:
- workaround for geth build

workaround for geth build

---

mt-batcher/services/sequencer/driver.go

Core changes:
- delete error judge logic
Notes:

[R4R]: delete error judge logic

---

packages/sdk/src/adapters/standard-bridge.ts

Core changes:
- Add testnet MNT token address compatibility
Notes:
- No
- No

[R4R]-{develop}:  handle testnet MNT token address compatibility

---

README.md

Core changes:
- Add Mainnet information to the README.

Add Mainnet information to the README.

---

gas-oracle/go.mod
gas-oracle/go.sum

Core changes:
fix go mod
Notes:
no
no

[R4R]-{develop}: Bugfix/fix gas oracle gomod

---

gas-oracle/Dockerfile

Core changes:
fix gasoracle gomod & docker file
Notes:
no
no

[R4R]-{develop}: fix gas-oracle dockerfile

---

gas-oracle/oracle/gas_price_oracle.go

Core changes:
fix block log query range
Notes:
no
no

[R4R]-{develop}: fix block log query range

---

packages/fault-detector/package.json
packages/message-relayer/package.json
packages/sdk/package.json

Core changes:
- update @mantleio/sdk to version 0.2.2
Notes:
- no
- no

update @mantleio/sdk to version 0.2.2

---

README.md

Core changes:
main into develop
Notes:
no
no

[R4R]-{develop}: Merge/main into develop
